version: '3.9'

services:
  app:
    container_name: mini_crm
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:Pomget231120@db:5432/mini_crm
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: db_mini_crm
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pomget231120
      POSTGRES_DB: mini_crm
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
